// Synthetic fixtures only. These are not operational credentials or personal records.
export const matchingCorpus = [
  { name: 'camel-case password', input: 'dbPassword=synthetic-value', output: 'dbPassword=<SECRET_1>' },
  { name: 'namespaced password', input: 'spring.datasource.password: synthetic-value', output: 'spring.datasource.password: <SECRET_1>' },
  { name: 'prefixed env password', input: 'PRODUCTION_DB_PASSWORD=synthetic-value', output: 'PRODUCTION_DB_PASSWORD=<SECRET_1>' },
  { name: 'AWS secret key context', input: 'AWS_SECRET_ACCESS_KEY=synthetic-value', output: 'AWS_SECRET_ACCESS_KEY=<SECRET_1>' },
  { name: 'refresh token', input: '{"refreshToken":"synthetic-refresh"}', output: '{"refreshToken":"<SECRET_1>"}' },
  { name: 'ID token', input: 'id_token=synthetic-id', output: 'id_token=<SECRET_1>' },
  { name: 'session token', input: 'SESSION_TOKEN=synthetic-session', output: 'SESSION_TOKEN=<SECRET_1>' },
  { name: 'bare token assignment', input: 'token: synthetic-token', output: 'token: <SECRET_1>' },
  { name: 'escaped double quote', input: 'password="alpha\\"bravo"', output: 'password="<SECRET_1>"' },
  { name: 'escaped backslashes', input: 'password="alpha\\\\bravo"', output: 'password="<SECRET_1>"' },
  { name: 'escaped single quote', input: "password='alpha\\'bravo'", output: "password='<SECRET_1>'" },
  { name: 'YAML doubled single quote', input: "password: 'alpha''bravo'", output: "password: '<SECRET_1>'" },
  { name: 'backtick assignment', input: 'password=`synthetic value`', output: 'password=`<SECRET_1>`' },
  { name: 'truncated quoted value', input: 'password="synthetic-value\nnext: safe', output: 'password="<SECRET_1>\nnext: safe' },
  { name: 'empty assignment newline', input: 'password:\nnext: safe', output: 'password:\nnext: safe' },
  { name: 'empty quoted assignment', input: 'password="" next=safe', output: 'password="" next=safe' },
  { name: 'do not match suffix key', input: 'notpassword=harmless supersecret=harmless', output: 'notpassword=harmless supersecret=harmless' },
  { name: 'metadata fields unchanged', input: 'token_count=20 password_hint=remember api_key_enabled=true secretName=demo', output: 'token_count=20 password_hint=remember api_key_enabled=true secretName=demo' },
  { name: 'null-ish assignments unchanged', input: 'password=null secret=undefined token=false api_key=example', output: 'password=null secret=undefined token=false api_key=example' },
  { name: 'JSON authorization header', input: '{"Authorization":"Bearer synthetic-token"}', output: '{"Authorization":"Bearer <BEARER_TOKEN_1>"}' },
  { name: 'single-quoted authorization', input: "{'authorization': 'Bearer synthetic-token'}", output: "{'authorization': 'Bearer <BEARER_TOKEN_1>'}" },
  { name: 'short contextual bearer', input: 'Authorization: Bearer abc123', output: 'Authorization: Bearer <BEARER_TOKEN_1>' },
  { name: 'Basic authorization', input: 'Authorization: Basic ZGVtbzpzeW50aGV0aWM=', output: 'Authorization: Basic <AUTH_CREDENTIAL_1>' },
  { name: 'proxy authorization', input: 'Proxy-Authorization: Basic ZGVtbzpzeW50aGV0aWM=', output: 'Proxy-Authorization: Basic <AUTH_CREDENTIAL_1>' },
  { name: 'Token authorization', input: 'Authorization: Token synthetic-token', output: 'Authorization: Token <AUTH_CREDENTIAL_1>' },
  { name: 'curl authorization', input: "curl -H 'Authorization: Bearer synthetic-token' https://example.test", output: "curl -H 'Authorization: Bearer <BEARER_TOKEN_1>' https://example.test" },
  { name: 'non-authorizing header unchanged', input: 'Authorization-Mode: Bearer optional\nX-Authorization: Bearer optional', output: 'Authorization-Mode: Bearer optional\nX-Authorization: Bearer optional' },
  { name: 'empty header does not eat next line', input: 'Authorization:\nBearer ordinary', output: 'Authorization:\nBearer ordinary' },
  { name: 'JSON cookie header', input: '{"Cookie":"sid=synthetic; csrf=synthetic-csrf","ok":true}', output: '{"Cookie":"<COOKIE_1>","ok":true}' },
  { name: 'indented cookie header', input: '  Cookie: sid=synthetic; theme=dark\n  Accept: text/plain', output: '  Cookie: <COOKIE_1>\n  Accept: text/plain' },
  { name: 'curl cookie header', input: "curl -H 'Cookie: sid=synthetic; csrf=second' https://example.test", output: "curl -H 'Cookie: <COOKIE_1>' https://example.test" },
  { name: 'set-cookie keeps enclosing JSON', input: '{"Set-Cookie":"sid=synthetic; Path=/; HttpOnly"}', output: '{"Set-Cookie":"<COOKIE_1>"}' },
  { name: 'header suffix not matched', input: 'lastcookie=safe Cookie-Policy=off', output: 'lastcookie=safe Cookie-Policy=off' },
  { name: 'URL key boundary', input: '?signature_version=2&tokenizer=foo&authMode=basic', output: '?signature_version=2&tokenizer=foo&authMode=basic' },
  { name: 'URL equals required', input: '?token&signature&auth', output: '?token&signature&auth' },
  { name: 'quoted URL keeps JSON valid', input: '{"url":"https://example.test/?token=synthetic"}', output: '{"url":"https://example.test/?token=<URL_SECRET_1>"}' },
  { name: 'URL percent encoded parameter name', input: '?access%5Ftoken=synthetic&ok=yes', output: '?access%5Ftoken=<URL_SECRET_1>&ok=yes' },
  { name: 'HTML query separator', input: '?ok=yes&amp;token=synthetic&amp;mode=fast', output: '?ok=yes&amp;token=<URL_SECRET_1>&amp;mode=fast' },
  { name: 'AWS presigned URL credentials', input: '?X-Amz-Credential=synthetic%2Fscope&X-Amz-Signature=synthetic-signature', output: '?X-Amz-Credential=<URL_SECRET_1>&X-Amz-Signature=<URL_SECRET_2>' },
  { name: 'Google signed URL signature', input: '?X-Goog-Signature=synthetic&ok=yes', output: '?X-Goog-Signature=<URL_SECRET_1>&ok=yes' },
  { name: 'invalid percent encoding unchanged', input: '?tok%GGn=safe', output: '?tok%GGn=safe' },
  { name: 'email log assignment key preserved', input: 'email=Alice@Example.Test', output: 'email=<EMAIL_1>' },
  { name: 'user email key preserved', input: 'user=alice@example.test', output: 'user=<EMAIL_1>' },
  { name: 'plus-address mailbox preserved as a whole', input: 'alice+demo=tag@example.test', output: '<EMAIL_1>' },
  { name: 'encrypted PEM key', input: 'before\n-----BEGIN ENCRYPTED PRIVATE KEY-----\nsynthetic-only\n-----END ENCRYPTED PRIVATE KEY-----\nafter', output: 'before\n<PRIVATE_KEY_1>\nafter' },
  { name: 'mismatched private PEM labels are still sensitive', input: '-----BEGIN RSA PRIVATE KEY-----\nsynthetic\n-----END EC PRIVATE KEY-----', output: '<PRIVATE_KEY_1>' },
  { name: 'public PEM key unchanged', input: '-----BEGIN PUBLIC KEY-----\nsynthetic\n-----END PUBLIC KEY-----', output: '-----BEGIN PUBLIC KEY-----\nsynthetic\n-----END PUBLIC KEY-----' },
  { name: 'enclosing secret must win inner URL', input: 'password="prefix?token=inner"', output: 'password="<SECRET_1>"' },
  { name: 'enclosing secret must win inner database URL', input: 'secret="prefix postgresql://demo:synthetic@example.test/db suffix"', output: 'secret="<SECRET_1>"' },
  { name: 'already redacted assignments unchanged', input: 'password=<SECRET_1> token="<SECRET_2>"', output: 'password=<SECRET_1> token="<SECRET_2>"' },
  { name: 'placeholder collision avoided', input: 'first=<SECRET_1> password=synthetic password=<SECRET_1>', output: 'first=<SECRET_1> password=<SECRET_2> password=<SECRET_1>' },
  { name: 'generic ID boundary strict', input: 'superuserId=ordinary userId=synthetic-user', output: 'superuserId=ordinary userId=<IDENTIFIER_1>', preset: 'strict' },
  { name: 'identifier escaped quote strict', input: 'userId="alpha\\"bravo"', output: 'userId="<IDENTIFIER_1>"', preset: 'strict' },
  { name: 'compact phone requires explicit context', input: 'phone=13800138000', output: 'phone=<PHONE_1>' },
  { name: 'plain compact numeric ID unchanged', input: 'order_id=13800138000', output: 'order_id=13800138000' },
  { name: 'phone pair retained separately', input: '202-555-0100 202-555-0101', output: '<PHONE_1> <PHONE_2>' },
  { name: 'phone newline pair retained', input: '202-555-0100\n202-555-0101', output: '<PHONE_1>\n<PHONE_2>' },
  { name: 'timestamp not a phone', input: '2026-01-01 12-34-56', output: '2026-01-01 12-34-56' },
  { name: 'phone disabled in secrets preset', input: 'phone=13800138000 password=synthetic', output: 'phone=13800138000 password=<SECRET_1>', preset: 'secrets' },
  { name: 'terminal POSIX home path', input: 'cwd=/Users/alice', output: 'cwd=/Users/<LOCAL_USER_1>' },
  { name: 'terminal Windows home path', input: String.raw`cwd=C:\Users\Alice`, output: String.raw`cwd=C:\Users\<LOCAL_USER_1>` },
  { name: 'lowercase Windows home prefix', input: String.raw`c:\users\alice\work`, output: String.raw`c:\users\<LOCAL_USER_1>\work` },
  { name: 'JSON Windows escaped path', input: String.raw`{"path":"C:\\Users\\Alice Smith\\work"}`, output: String.raw`{"path":"C:\\Users\\<LOCAL_USER_1>\\work"}` },
  { name: 'quoted spaced POSIX path', input: '"/Users/Alice Smith/work"', output: '"/Users/<LOCAL_USER_1>/work"' },
  { name: 'existing path placeholder stable', input: '/home/<LOCAL_USER_2>/a /home/<LOCAL_USER_1>/b', output: '/home/<LOCAL_USER_2>/a /home/<LOCAL_USER_1>/b' },
  { name: 'website home paths unchanged', input: 'https://example.test/home/alice', output: 'https://example.test/home/alice' },
  { name: 'raw quoted cookie contents', input: 'Cookie: sid="synthetic"; other=second', output: 'Cookie: <COOKIE_1>' },
  { name: 'raw quoted Set-Cookie contents', input: 'Set-Cookie: sid="synthetic"; Path=/', output: 'Set-Cookie: <COOKIE_1>' },
  { name: 'curl header with internal quotes', input: `curl -H 'Cookie: sid="synthetic"; other=second' https://example.test`, output: `curl -H 'Cookie: <COOKIE_1>' https://example.test` },
  { name: 'bearer before comma log field', input: 'Authorization: Bearer abcdefgh, Content-Type: text/plain', output: 'Authorization: Bearer <BEARER_TOKEN_1>, Content-Type: text/plain' },
  { name: 'bearer before closing brace', input: '{Authorization: Bearer abcdefgh}', output: '{Authorization: Bearer <BEARER_TOKEN_1>}' },
  { name: 'redis password with empty username', input: 'redis://:synthetic-password@localhost:6379/0', output: 'redis://:<DATABASE_PASSWORD_1>@localhost:6379/0' },
  { name: 'database password containing at sign', input: 'postgres://demo:synthetic@password@localhost/db', output: 'postgres://demo:<DATABASE_PASSWORD_1>@localhost/db' },
  { name: 'contextual Chinese mobile number', input: '手机号：13800138000', output: '手机号：<PHONE_1>' },
  { name: 'Chinese order number remains unchanged', input: '订单号：13800138000', output: '订单号：13800138000' },
];
